const count = 5;
console.log('count:', count);
console.log('jacob Mercer');
console.log(26);
// const age = 20;
// console.log(age);
// const username = 'Mango';
console.log('Mango');
const gogo = 'script';
console.log('gogo', gogo);
const alex = 61;
console.log('alex', alex);
// const productName = 'Droid';
// const pricePerItem = 2000;
// let username = 'Mango';
// username = 'Poly';
// console.log(username);
// ----------------------
// let pricePerItem = 2000;
// pricePerItem = 3500;
let productName = 'Droid';
productName = 'Repair droid';
console.log(productName);
const topSpeed = 160;
const distance = 617.54;
const isAdmin = false;
console.log('isAdmin', isAdmin);
// let userName;
// console.log(userName);
const quantity = 17;
console.log(typeof quantity);
// const message = 'js is awesome';
// console.log(typeof message);
const status = null;
console.log(typeof status);
const isYouAre = 'true';
console.log(typeof isYouAre);
const x = 8;
const y = 7;
console.log(x + y);
console.log(x - y);
console.log(x * y);
console.log(x / y);
console.log(x % y);
console.log(x ** y);
const pricePerItem = 3500;
const orderedQuantity = 4;
// const totalPrice = 14000;
console.log(pricePerItem * orderedQuantity);
const totalPrice = pricePerItem * orderedQuantity;
console.log(totalPrice);
let z = 18;
// let a = 1;
// console.log((z += a));
// console.log((z -= a));
// console.log((z *= a));
// let age = 25;
// // age = age + 1;
// age += 1;
// console.log('age', age);
// let a = 5;
// let b = 10;
// let c = 15;
// let d = 20;

// Change code below this line
// a += 2;
// b -= 4;
// c *= 3;
// d /= 10;
// d **= 2;
// d %= 3;
// console.log(a);
// console.log(b);
// console.log(c);
// console.log(d);
// const message = 'Mangj ' + 'is' + ' happy';
// console.log(message);
const phrase =
  'i' + ' am' + ' happy' + ' now' + ' because' + ' now' + ' I' + ' know';
console.log(phrase);
let age = 25;
// const message = 'Poly is ' + age + ' years old';
// console.log(message);
console.log('Mango ' + 55);
console.log(1 + '2' + 3);
console.log(1 + 2 + '3');
const userName = 'Poly';
const message = 'Welcome ' + userName;
console.log(message);
